[project]
authors = ["GondekNP <npg@berkeley.edu>"]
channels = ["conda-forge"]
description = "A demo devcontainer pixi setup"
name = "devcontainer_template"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
pytesseract = ">=0.3.13,<0.4"
pdf2image = ">=1.17.0,<2"
pandas = ">=2.2.3,<3"
numpy = ">=2.0.2,<3"
pdfplumber = ">=0.11.5,<0.12"
